{% set name = "sstp-client" %}
{% set version = "1.0.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/{{ name }}/files/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha1: 965ab9f4f3ade5cd6ffd0985c0aa66b475e1e44f

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
  host:
    - libevent
    - openssl
  run:
    - libevent
    - openssl

test:
  commands:
    - sstpc --help

about:
  home: http://sstp-client.sourceforge.net/
  license: GPL-2.0
  license_file: COPYING
  license_family: GPL
  summary: SSTP (Microsofts Remote Access Solution for PPP over SSL) client

  # The remaining entries in this section are optional, but recommended
  description: |
    SSTP is Microsofts Remote Access Solution (RAS) for PPP over SSL. It can
    be used instead of PPTP or L2TP, and is only available with Windows
    Vista/7 connecting to a Windows 2008 Server. The advantage of SSTP
    compared to PPTP and L2TP is that it cannot be easily blocked by
    firewalls since the traffic is transmitted over HTTPS on port 443.
    Windows Vista/7 uses SSTP if PPTP or L2TP cannot be established. For
    further information on SSTP check out wikipedia's article on Secure
    Socket Tunneling Protocol.

    http://en.wikipedia.org/wiki/Secure_Socket_Tunneling_Protocol
  dev_url: https://sourceforge.net/projects/sstp-client/

extra:
  recipe-maintainers:
    - asmeurer
