travis:
  secure:
    BINSTAR_TOKEN: PWuhvLtzZuLLvQ+FQI2Dnm2ZHr85a4J0LnnVTh/lqk0BVTk1dRe/vS5Ys8LvbLklCiE2Di1VaxcH5GmlCdyqORtX2t0/M6briQaW3JEyzf1KAgXZCQxxMM5BT1W8DzIt8VI04Dt1B8v1oQrkd3PP66hg2BJLaFfNae0WgEtp0Zo+Xm3PYRoUvUvC+UBjyHOsxeKu8wsYpY8zi0BsP9DAx4R+i+ood9SlY9Vk+INkCvhSbNdQb/CsSGfH6GoodoH5RkkkJOjtlCQ0tFJhf8oXAnr2F0qvBuoCafnG/m4oAvh/jOXQ08wSf0g2qRIUWAKBdqvn/4rUQxkPdSPOMUKYAL29sYQTNebVU7cVahljVSRH0x/HalHMTRFtnseywgCJI2vRhRXXbfoJ1P6yhgn86ZeRQTF6huUjSOBAgclysMUS7jNDCUPHC49B2YSz6Rkbe1NW6xEyopdS0mFgovabNAeGptt6OKQvauKfkBlKId2Z5yTbtGRd4zcuaYR2tx4LPKDzhpIABsAounlrmNka9+qjJAAM98AD2FXdorTgK/CDwKzVGeywLK96SgFQRmZHVMC+d4jxiiFtaIuen4PpBI8jM2D46QxP484Q+ATHZDTELGLCubR4XqZkWhW4sGBF6YXqWkuA0SX+fws68cj5O4UNSY7kUheUo2TsO9dgaZg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
