travis:
  secure:
    BINSTAR_TOKEN: n+u/iGF//uH7P0TDWbYllgtnNzMUq1c0FDbGmdz1bLQeZ+NNQ+emy8sE2JP0s869x/tWXQec7gAavARmYbDiBpWW8RcdTHHcVeh9pprnxEPuOOToi/L+znu4fy/tOoR4jt5qCpVXBKNcuRtgyxLhUOWVNfcVdboaIlq6tYdKTVvgF2yjMDLeTK9GWXmQOLYLxHgUUIdcBWF+/IITOP8UY41zF/6ND8TndYE/t0xjir+nCe6hWjB3W9q0ybSyuR2iz/Dt3Ju1ZrrJlf1O/skjrv9VMa0fhB7KSVQeXm+htQaxvnHuR1UgVKqKIAM28SA2Q569farcunGwY92A3NBQGeiBonC7LzC29RRr8QWys+3d9c/A07kXoDLJgS6FNGDv0dbWfVzRFTuAD4UCicfQfp84bJmOFnKUIYLBOffQroTj6YOlAC/huLh4XGBZdPaapuO9lQCIUgEmwDn/y1MnqhFYAdPh8plG8x/wQCowp3+YFf0HAdjXkN8MqWc1rPnE3feyKQZLPtV9UvhHiE9ZtVCDJtJCoWxO0e2GHa6znWxHi5Xmo6QirinEpFMfN02ZRNrKDvgNHbTlatm2tkj6jf5YT3gTO6pHsAXzttWO+7bkJ55LaJFh55VEXUSXsbJtZReBlQXdGAlxE9E++EyITrOQwbk1qEHv6P9OwCpbr/M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
